### ISSUE TITLE
extension: container backup

### ISSUE THREAD

**Issue by ehazlett** [shipyard/shipyard#279]

**Comment by Braintelligence** [comment]
👍 Is there something new about this? Couldn't find anything in the docs about "backup" of containers.

**Comment by tombee** [comment]
@Braintelligence 
There isn't, I think this might have been closed since it's less relevant with named volumes being available.  

If you have a proposal or a suggested use-case, feel free to file an issue or proposal PR.  Thanks!

**Comment by Braintelligence** [comment]
@tombee Thanks for clarifying! I'm a bit new to the docker business, could you please elaborate or provide a link to how named volumes make backups of containers less needed? That would be really helpful :). 👍

**Comment by tombee** [comment]
@Braintelligence 
A common pattern was to use a container as a data-only store.  It would serve as just a shell that exposed a directory as a data volume.  This way, an application container could be restarted, re-created, removed, upgraded and so on without the loss of data inside the container. This tended to be the recommended approach rather than using bind mounts, as the container could isolate the data entire and no assumptions of the underlying filesystem were required.

You can still see this pattern documented in places such as the Jenkins image, it suggests creating a secondary container that acts as a "Volume Container": https://hub.docker.com/_/jenkins/

As of Docker 1.9~ or so, named volumes were introduced so that data-only containers weren't required.  First-class named volumes were introduced to isolate state from containers (a discussion around https://github.com/docker/docker/issues/17798).

The questions now are probably: 

* How do we provide backup functionality for volumes within shipyard? 
* Is this a shipyard concern? If not, how do we guide/educate a user into setting this up outside of shipyard
* Should this be handled by the configured volume driver? If so, how do we guide a user into setting up the correct configuration

**Comment by Braintelligence** [comment]
@tombee Thank you again for your insight. What do you think about using
`docker commit`
for backing up containers, though?
