### ISSUE TITLE
Impossible to put Shipyard UI behind nginx

### ISSUE THREAD

**Issue by bieniek** [shipyard/shipyard#587]
Hi, 

I've got big problem with hiding Shipyard UI behind nginx. All redirections are based on '/' so any forwarding of type

host:port:8080/#/dashboard -> host/shipyard/#/dashboard

are impossible. 

Shipyard version:
"Created": "2015-03-03T00:50:19.908335336Z"

**Comment by ehazlett** [comment]
Hmm I will see if we can add something.

**Comment by swege** [comment]
@bieniek I had this issue with a couple of web applications. The simplest solution is to use a dedicated subdomain for shipyard. I've got it up and running with the following nginx configuration (note that I also do not run the container with -p 8080:8080 since the [ufw rules are not working together with docker](http://stackoverflow.com/questions/30035206/ubuntu-ufw-how-to-tell-docker-not-to-expose-all-ports))
```
server {
        listen                  443 ssl;
        server_name             shipyard.example.com;
        ssl_certificate         /etc/nginx/ssl/example.com.crt;
        ssl_certificate_key     /etc/nginx/ssl/example.com.key;
        add_header              Strict-Transport-Security max-age=315360000;
        add_header              X-Frame-Options DENY;
        auth_basic              "Private";
        auth_basic_user_file    /etc/nginx/htpasswd/shipyard.example.com;

    location / {
        proxy_pass      http://172.17.0.22:8080/;
        proxy_redirect  http://172.17.0.22:8080/ https://$server_name/;
    }
}
```

I don't think it is worth fixing anything in shipyard since this workaround is quite simple.

**Comment by ehazlett** [comment]
This would require some significant updates on the routing and authentication system.  I think the recommended path at this point would be to use a subdomain as @swege recommends.
