### ISSUE TITLE
Lack of Container APIs in the Documentation

### ISSUE THREAD

**Issue by abhishekbsharma** [shipyard/shipyard#594]
I was using the older version of Shipyard for a project and today my script broke. Why did we remove the container start APIs? How do I start a docker container programmatically using Shipyard now ? 
I don't see documentation for the Container APIs.

* Note: I am not cutting-edge current on Docker developments.

**Comment by ehazlett** [comment]
As noted here (https://shipyard-project.com/docs/api/#docker) we support
the full Docker Remote API.  Rather than duplicating the official Remote
API docs, we chose to just link to the official ones.  You can see how to
create and start a container here:
https://docs.docker.com/reference/api/docker_remote_api_v1.20/#create-a-container
