### ISSUE TITLE
Is pause and unpause support on the way?

### ISSUE THREAD

**Issue by RustJason** [shipyard/shipyard#621]
If it is not, I would be happy to do so. include ```docker commit``` ect

**Comment by tombee** [comment]
Hey Jason,

Sure -- feel free to submit a PR for pause/unpause.

I'm not sure about the usefulness of commit in this instance though -- I'll
defer to @ehazlett on that.

**Comment by ehazlett** [comment]
Pause and unpause would be fine.  I don't think we would do commit as that
would commit local to the engine and Shipyard is aimed towards clustered
Swarm deployments.

**Comment by RustJason** [comment]
pause and unpause are done. But sometimes we want to make a new image by our running containers. would be terrific simple click commit to make a local image ?

**Comment by tombee** [comment]
@RustJason thanks for the PR -- looking good!

Could you give an example of a use case when you might be committing and running containers via the shipyard UI?  

For me it doesn't quite fit with how I'd typically use swarm & shipyard.

**Comment by RustJason** [comment]
Hum......  Maybe just because I did't use docker in the right way, yesterday I used docker to run a Rust Hello World program, but I found I it was running in debuging mode, cause I forget to add ```---release``` parameters, code had been successfully compiled in that container. So what I want to do is to stop this container and commit it as a new image then rerun a new one in release mode.

Maybe I should use ```-v``` to bind my source folder to the container, so I don't need to save that container ?
Does this make scene?

**Comment by tombee** [comment]
These are good questions..

It's a little difficult to answer, and it depends what you're trying to achieve here.  I wouldn't recommend using `docker commit` as a workflow for updating your containers/images.  The reason is that these steps performed ad-hoc become difficult to track and reproduce when you need to build a new image from the original `Dockerfile`.

For production/staging use, I would strongly recommend that you add the `--release` parameter into your `Dockerfile`'s `CMD` or `ENTRYPOINT` and then rebuild and push the image out to the hosts that it should run on.

For local development, you may be able to use something like `docker-compose` to wire together your containers.  With compose you should be able to override the default `CMD`/`ENTRYPOINT` to remove the `--release` parameter.

As for the `-v`/`--volume` flag, again.. this depends.  It can sometimes make sense to add this when developing locally to speed up incremental builds, but I would advise against doing this in your deployed environment since it creates a dependency upon a particular directory being available so that you can run your app.  You would then need to find a way to keep this in sync and prevent drift.

Be sure to call by freenode #shipyard and #docker, you can give us a shout if something's unclear here.

**Comment by ehazlett** [comment]
There is also the case to use data volumes.  This would eliminate the need
for a specific directory and still give you the persistence without losing
the ephemeral data.  Also, volume management is coming in Docker 1.9 so it
will be easier.

**Comment by RustJason** [comment]
Got that.

**Comment by RustJason** [comment]
https://github.com/shipyard/shipyard/pull/622
