### ISSUE TITLE
How to choose swarm node when deploy container 

### ISSUE THREAD

**Issue by nthien** [shipyard/shipyard#635]
How to choose swarm node when deploy container  ?

**Comment by ehazlett** [comment]
You will need to use the Swarm constraints.  See http://docs.docker.com/swarm/scheduler/filter/

**Comment by kdubb1337** [comment]
@nthien you should put 'node' as the name of the constaint and then the value is the name of your node.

After searching for hours I finally realized it wasn't working for me because there is a bug in shipyard. If you enter a constraint that doesn't exist on the first pass it will just keep pushing more constraints into the array it is sending to the backend.

**Comment by kdubb1337** [comment]
I've submitted a pull request which may fix the issue. https://github.com/shipyard/shipyard/pull/854
