### ISSUE TITLE
Container logs choke angular sanitization parser

### ISSUE THREAD

**Issue by cedwards-reisys** [shipyard/shipyard#676]
Cannot view logs due to javascript error:

http://cl.ly/image/3r31341M243t

This happened after upgrading to Docker 1.9

Here is log content returned from the shipyard api:
[cfda-program-container-log.txt](https://github.com/shipyard/shipyard/files/40345/cfda-program-container-log.txt)

**Comment by dddanmar** [comment]
Same issue here -- Log page loads but does not render any content.

Interestingly #677 and #676 both are having issues related to Spring - I am also trying to output Spring logs and Angular's parser is erroring out. I wonder there is some magical escape character present in Springs build/startup that is causing the problem here.

[My Shipyard log API response](https://github.com/shipyard/shipyard/files/127696/parse_error.txt)

**Comment by tombee** [comment]
@dddanmar Would you be able to test out PR #749 to see if it fixes your issue?
