### ISSUE TITLE
Container status bug in container view

### ISSUE THREAD

**Issue by Tochirou** [shipyard/shipyard#728]
I have, lets say, a wordpress container. Set on "Always restart".

Problem is, at a certain point, on the container overview the container appears as if it was down:
![bug](https://cloud.githubusercontent.com/assets/6116092/12351291/d05fd3c8-bb7c-11e5-94b1-6ac7ecb1f2b5.png)

When I go on the container view, I can see that, in fact, it's up.

![bug2](https://cloud.githubusercontent.com/assets/6116092/12351300/d378644e-bb7c-11e5-9f24-610c9c61e3c7.png)

And I can confirm this because I can access to the wordpress application.
It'll be great if it could be fixed :)

**Comment by ehazlett** [comment]
This is because it's in a restarting state.  This should resolve once the container comes back.

**Comment by mujiburger** [comment]
I think this is actually a bug.

shipyard version 3.0.3

<img width="1623" alt="screen shot 2016-04-02 at 8 20 06 am" src="https://cloud.githubusercontent.com/assets/7569921/14226278/e19ef706-f8ab-11e5-9a69-11275155fd73.png">
<img width="643" alt="screen shot 2016-04-02 at 8 19 43 am" src="https://cloud.githubusercontent.com/assets/7569921/14226284/f28d42d4-f8ab-11e5-84b1-401bf6faa4ca.png">

**Comment by mujiburger** [comment]
It appears that docker doesn't remove the "restarting" status in `/containers/json` after automatic restarts because of failure.  That actually makes sense.  Not a bug here or there.  It would be nice if docker would provide a way to update that status without restarting the container, but it doesn't appear that they do right now.  It looks like a machine readable status field is being added to the endpoint soon: docker/docker#18966.  That would make it possible to display a yellow marker or something else to distinguish containers that are currently running, but had a problem at one point.
