### ISSUE TITLE
"Gateway Timeout" Error...

### ISSUE THREAD

**Issue by haoyixin** [shipyard/shipyard#729]
Error...
{"data":"Gateway Timeout","status":504,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, _/_","X-Access-Token":"admin:$2a$10$IDLkMaVg0Oi7LRypU6SoieLj9Uu6tVUsh16I9eBQ5YpcHbMGtHmzW"}},"statusText":"Gateway Timeout"}

curl http://localhost:3375/containers/json?all=1
.................................
.....right response.....
.................................

2375 for docker, 3375 for swarm manage, everything is ok but shipyard

when i use:
tcpdump -i eth0 port 3375(when i was accessing shipyard-ui)
..............................
0 packets captured
...............................

**Comment by haoyixin** [comment]
it could work with docker daemon on 2375 but not work for swarm on 3375

**Comment by ehazlett** [comment]
How did you install?

**Comment by haoyixin** [comment]
docker run     -d     --net overlay.zzbc2     -p 8080:8080     --restart=always     --name controller.shipyard.meng8.se.overlay.zzbc2     shipyard/shipyard:latest     server     -d tcp://manage.swarm.meng8.se.zzbc2.qihoo.net:3375     --rethinkdb-addr rethinkdb.shipyard.meng8.se.overlay.zzbc2 --disable-usage-info
i pulled latest image from docker hub and run it...

**Comment by kayone** [comment]
I'm having the same issue, installed using the recommended method,

`curl -k -sSL https://shipyard-project.com/deploy | ACTION=deploy bash -s`

**Comment by haoyixin** [comment]
@kayone  Did it be solved?

**Comment by kayone** [comment]
I ended up upgrading docker and reinstalling shipyard which fixed the issue.

**Comment by gw0** [comment]
I experienced the same problem using recommended method with Docker 1.10 and 1.11.1 on Ubuntu 15.10 (kernel 4.2.0-36-generic, repository deb https://apt.dockerproject.org/repo ubuntu-wily main). I ended up removing Shipyard, removing/purging Docker completely (also removing its graph folder and additional Docker daemon parameters), and freshly reinstalling everything.

After dissecting all the changes I found out that the `--icc=false` parameter is causing problems. Docker daemon command line:

```
# not working:
/usr/bin/docker daemon -H fd:// --storage-driver=overlay --icc=false --iptables=true
# working:
/usr/bin/docker daemon -H fd:// --storage-driver=overlay --iptables=true
```

It seems that the problem/solution is connected with Docker networks, because Shipyard does not seem to use them:

```
# docker network ls
NETWORK ID          NAME                DRIVER
576a269e0f12        bridge              bridge              
637d7f610125        host                host                
f572f933d118        none                null
```

So please either add all Shipyard containers to a separate network or introduce a docker-compose deployment that does this.

**Comment by kayone** [comment]
> So please either add all Shipyard containers to a separate network or introduce a docker-compose deployment that does this.

Please make shipyard a compose app!

**Comment by ehazlett** [comment]
@kayone you mean like https://github.com/shipyard/shipyard/blob/master/docker-compose.yml
