### ISSUE TITLE
accessing specific containers to specific users

### ISSUE THREAD

**Issue by Ara4Sh** [shipyard/shipyard#811]
Hello 

the main reason we choose shipyard is our developers manage containers through web interface . 
but now we figured out we cant access the specific containers to 1 users if we choose container in role the users can see list of all containers from all nodes and access to all of them . 

what do you suggest to me ?

**Comment by jmzwcn** [comment]
Yes, how should let user only view/operate his/her self container?

**Comment by tombee** [comment]
Shipyard isn't able to deny access on a container-by-container basis at the moment since we don't have fine grained controls in the basic RBAC implemented currently.  

If anyone has ideas on how to implement this, I recommend [opening up a proposal PR](https://docs.docker.com/v1.5/project/advanced-contributing/) :smile:
