### ISSUE TITLE
Security issues with Shipyard?

### ISSUE THREAD

**Issue by mgielissen** [shipyard/shipyard#835]
I had 2 servers with Shipyard running, they both had strange processes running like /usr/bin/iptab (100% cpu) and /usr/bin/.ssh. Also there where iptables rules added:

Chain INPUT (policy ACCEPT)
target     prot opt source               destination
DROP       all  --  23.234.14.119        anywhere
DROP       all  --  222.174.5.42         anywhere
ACCEPT     tcp  --  121.12.125.0/24      anywhere             tcp dpt:2375
ACCEPT     tcp  --  23.234.30.0/24       anywhere             tcp dpt:2375

**Comment by ehazlett** [comment]
Are these instances accessible to the public?  If so you should use TLS as
recommended in the docs.

**Comment by John-Lin** [comment]
@ehazlett @mgielissen I have same issue with it. I deployed the shipyard server on the public.

A few days later, I got suspected malicious IP address connected to shipyard docker image

<img width="1252" alt="screen shot 2016-07-09 at 2 52 53 am" src="https://cloud.githubusercontent.com/assets/4214069/16698402/a525ccec-4580-11e6-9389-83af9305ff1b.png">

And I found my server has been hacked and running a malicious program

<img width="1208" alt="screen shot 2016-07-09 at 2 47 20 am" src="https://cloud.githubusercontent.com/assets/4214069/16698425/c5c449f6-4580-11e6-8a6d-5d14e171a100.png">

The “2498” program reported as malicious form virustotal
https://www.virustotal.com/en/file/3dddc7bda6f1b8bef320d2046199cc8ae4cf715e7216cc221171a268f671ff10/analysis/

**Comment by mgielissen** [comment]
It's generating a lot of outbound traffic.

**Comment by John-Lin** [comment]
Yes, indeed. My server generated about 900GB in 5 days.

**Comment by matthewmacaulay** [comment]
We noticed the same issue. 

Reviewing the logs on the host server looks like it was being used as part of a DDoS attack.
Indeed the malware installed seems to be used exclusively for DDoS. "Portbet" - md5sum 98eb47a21ffeb1ed1966f89375e843c3 this is different to the one John-Lin posted. 

The attacker seems to have been able to connect to the host from the docker container, we are going to look at namespaces to avoid giving root to compromised containers in the future.  There was a good presentation about namespaces at BSides London a few feeks back: https://www.youtube.com/watch?v=uQigvjSXMLw

The attacker has tried to cover their tracks by deleting files and logs, luckily the diskspace had not been overwritten so I could recover the files to try and workout what they were up to. 

The attacker also seems to have created a local account and home dir which contained the malware. 

At the moment we are assuming a vulnerability exists within the shipyard container, but as yet I have not identified it. Anyone else had any luck identifying the route in?

**Comment by ehazlett** [comment]
There is no vulnerability in the container. You are effectively opening up
your host to the public. (this is the same as the docker docs where they
state to use TLS if it's public which we do the same).

On Jul 11, 2016 04:20, "Mat MacAulay" <notifications@github.com> wrote:

We noticed the same issue.

Reviewing the logs on the host server looks like it was being used as part
of a DDoS attack.
Indeed the malware installed seems to be used exclusively for DDoS.
"Portbet" - md5sum 98eb47a21ffeb1ed1966f89375e843c3 this is different to
the one John-Lin posted.

The attacker seems to have been able to connect to the host from the docker
container, we are going to look at namespaces to avoid giving root to
compromised containers in the future. There was a good presentation about
namespaces at BSides London a few feeks back:
https://www.youtube.com/watch?v=uQigvjSXMLw

The attacker has tried to cover their tracks by deleting files and logs,
luckily the diskspace had not been overwritten so I could recover the files
to try and workout what they were up to.

The attacker also seems to have created a local account and home dir which
contained the malware.

At the moment we are assuming a vulnerability exists within the shipyard
container, but as yet I have not identified it. Anyone else had any luck
identifying the route in?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/shipyard/shipyard/issues/835#issuecomment-231696726>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAP6IrxYjcGsBdPIo1RXYTsge8A27cEsks5qUhj1gaJpZM4I-ZeA>
.

**Comment by blade254353074** [comment]
Our server has been DDOS attacked twice, because of shipyard. 😭
