### ISSUE TITLE
How does shipyard integrate with docker-swarm? 

### ISSUE THREAD

**Issue by dlaub3** [shipyard/shipyard#889]
It's my understanding that shipyard works with docker swarm. So my question is in docker 1.12 does shipyard need to be secured with TLS since docker does this by default? Also, can the shipyard controller be used as a standalone interface for docker swarm? Many thanks.  

p.s. I'm new to github. Is it acceptable to ask these types of questions here? I couldn't decided where to ask.

**Comment by ehazlett** [comment]
Currently shipyard works with swarm but not yet swarm mode which is new in
docker 1.12. We are working on a branch to support this which would support
all of the built-in security once finished.

**Comment by cloutiertyler** [comment]
Is there anything I could do to help out with this effort? Is there a list of targets somewhere?

**Comment by cloutiertyler** [comment]
Actually, I see that the front end doesn't display in Safari, so I think I'll start with that.

**Comment by cloutiertyler** [comment]
Created pull request #939

**Comment by tombee** [comment]
@cloutiertyler There's lots of work remaining on the `swarm-mode` branch that we'd love help with.  The simplest things are just fleshing out our "Create" and "Inspect" pages for each of the resources (Services, Containers, Volumes, Networks, etc.).

If you're interested in tackling something a bit different to that, there are a few items in: https://github.com/shipyard/shipyard/blob/swarm-mode/ui/todo.md

If you have any questions, feel free to give us a shout!

**Comment by cloutiertyler** [comment]
Okay, fleshing out the "Create" and "Inspect" pages sounds good. I noticed when I was using it that I had to hop over to command line for a lot of things, so I might try to work in some of the more important ones. I'll probably work on these first.

Also, I was thinking I might try integrating a component which is something like https://github.com/ManoMarks/docker-swarm-visualizer, just because it looks super fun. Not sure if that's what you guys are going for though lol.

**Comment by tombee** [comment]
Awesome, sounds good.  I just haven't had the spare time to map out the rest of the API, so that would be a huge bonus.  Thanks for your interest and help! :smile: 

I think the plan at the moment is just get it back to a basic level of functionality, similar to the angular UI and then we can start adding bells and whistles :smile:.

**Comment by cloutiertyler** [comment]
It looks like most of the API (back end) is just proxied swarm APIs. So I think I'll just go through those adding UI to each of them. I'd like to bring it up to par with as much command line functionality as I can.
