### ISSUE TITLE
centos 6 with docker 1.7.1 problem

### ISSUE THREAD

**Issue by douglas-lee** [shipyard/shipyard#934]
when finish the deployment, but cannot view any containers and images.

**Comment by ehazlett** [comment]
Shipyard doesnt support that old of docker. Try 1.11 or higher

**Comment by systemroot** [comment]
Hello @ehazlett 
i'm replying here as is the same issue about "centos"
my host where docker ```Server Version: 17.06.1-ce``` is installed is `Ubuntu 14.04`
I'm trying to deploy a container from shipyard gui with `centos:6.9` but after 2-3 minutes container gets deleted automatically. i've also tried centos 7, 6.8 the same problem happen. i just need to deploy centos 6.9 cause i need to do some tests, do you know any fix about this because i'm not finding what's wrong with it :confused:
