### ISSUE TITLE
nodes are not recognized when running on docker swarm

### ISSUE THREAD

**Issue by igal-dahan** [shipyard/shipyard#965]
Hi,

I have deploy the docker-compose.yml from the swarm-mode branch by the docker stack command:

#> docker network create --driver=overlay shipyard
#> docker stack deploy --compose-file ~/shipyard/docker-compose.yml shipyard

i have added those line to each service in the compose file:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
        constraints: [node.hostname == swarm-master-3]

that cause to run all services in same node manager

i am able to login and see things, But the nodes i have in the swarm cluster are not recognized.

1. is this branch support for now the swarm cluster?
2. if yes, what could be the issue i cannot see nodes and services?

BR
Igal

**Comment by ehazlett** [comment]
The `swarm-mode` branch is a work in progress.  It does not support everything yet but you should be able to see services.

/cc @tombee

**Comment by tombee** [comment]
@igal-dahan 
At the moment, you won't be able to see containers and images etc. that are not on the node where shipyard is running.  We're proxying API calls to the docker socket, so that calls to `/services` work (as @ehazlett states), but the problem is that swarm mode doesn't support an equivalent of `/containers/json` that returns a cluster-wide list of what's running.  We'll have a solution to this ASAP :smile:

**Comment by igal-dahan** [comment]
:+1: 
:-)

**Comment by Noah87** [comment]
At the risk of reviving an old thread .. I was wondering if a solution has been found concerning Shipyard and Swarm.

thanks !
